/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "denuncia" CASCADE;

DROP TABLE IF EXISTS "pessoa" CASCADE;

DROP TABLE IF EXISTS "auditoria" CASCADE;

DROP TABLE IF EXISTS "usuariopapel" CASCADE;

DROP TABLE IF EXISTS "usuario" CASCADE;

DROP TABLE IF EXISTS "papel" CASCADE;

CREATE TABLE "papel" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "permissoes" TEXT NOT NULL);

CREATE TABLE "usuario" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "rg" TEXT NOT NULL,
  "cpf" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "sobrenome" TEXT NOT NULL,
  "hash_senha" TEXT NOT NULL,
  "data_cadastro" TEXT NOT NULL,
  "ultimo_acesso" TEXT NOT NULL);

CREATE TABLE "usuariopapel" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "usuario" INTEGER NOT NULL,
  "papel" INTEGER NOT NULL,
  "valido" BOOLEAN NOT NULL);

CREATE TABLE "auditoria" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "acao" TEXT NOT NULL,
  "usuario" INTEGER NOT NULL);

CREATE TABLE "pessoa" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "estado" INTEGER NOT NULL,
  "cpf" TEXT NOT NULL,
  "rg" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "sobrenome" TEXT NOT NULL,
  "ultima_modificacao" INTEGER NOT NULL);

CREATE TABLE "denuncia" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "latitude" DOUBLE PRECISION NOT NULL,
  "longitude" DOUBLE PRECISION NOT NULL,
  "endereco" TEXT NOT NULL,
  "pessoa" INTEGER NOT NULL,
  "detalhes" TEXT NOT NULL,
  "usuario" INTEGER NOT NULL,
  "data_hora_visto" TEXT NOT NULL);

