/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "denuncia_localizacoes" CASCADE;

DROP TABLE IF EXISTS "denuncia" CASCADE;

DROP TABLE IF EXISTS "pessoa_apelidos" CASCADE;

DROP TABLE IF EXISTS "pessoa" CASCADE;

DROP TABLE IF EXISTS "auditoria" CASCADE;

DROP TABLE IF EXISTS "usuariopapel" CASCADE;

DROP TABLE IF EXISTS "usuario" CASCADE;

DROP TABLE IF EXISTS "papel" CASCADE;

CREATE TABLE "papel" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "permissoes" TEXT NOT NULL);

CREATE TABLE "usuario" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "rg" TEXT NOT NULL,
  "cpf" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "sobrenome" TEXT NOT NULL,
  "hash_senha" TEXT NOT NULL,
  "data_cadastro" TEXT NOT NULL,
  "ultimo_acesso" TEXT NOT NULL);

CREATE TABLE "usuariopapel" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "usuario" INTEGER NOT NULL,
  "papel" INTEGER NOT NULL,
  "valido" BOOLEAN NOT NULL);

CREATE TABLE "auditoria" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "acao" TEXT NOT NULL,
  "usuario" INTEGER NOT NULL);

CREATE TABLE "pessoa" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "cpf" TEXT NOT NULL,
  "rg" TEXT NOT NULL,
  "nome" TEXT NOT NULL);

CREATE TABLE "pessoa_apelidos" (
  "object_id" BIGINT NOT NULL,
  "index" BIGINT NOT NULL,
  "value" TEXT NOT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "pessoa" ("id")
    ON DELETE CASCADE);

CREATE INDEX "pessoa_apelidos_object_id_i"
  ON "pessoa_apelidos" ("object_id");

CREATE INDEX "pessoa_apelidos_index_i"
  ON "pessoa_apelidos" ("index");

CREATE TABLE "denuncia" (
  "id" INTEGER NOT NULL,
  "valido" BOOLEAN NOT NULL,
  "pessoa" INTEGER NOT NULL PRIMARY KEY,
  "ultima_localizacao" TEXT NOT NULL,
  "usuario_cadastro" INTEGER NOT NULL,
  "usuario_ultima_atualizacao" INTEGER NOT NULL,
  "data_denuncia" TEXT NOT NULL);

CREATE TABLE "denuncia_localizacoes" (
  "object_id" INTEGER NOT NULL,
  "index" BIGINT NOT NULL,
  "value" TEXT NOT NULL,
  CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "denuncia" ("pessoa")
    ON DELETE CASCADE);

CREATE INDEX "denuncia_localizacoes_object_id_i"
  ON "denuncia_localizacoes" ("object_id");

CREATE INDEX "denuncia_localizacoes_index_i"
  ON "denuncia_localizacoes" ("index");

