// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ALL_CLASS_ODB_HXX
#define ALL_CLASS_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "AllClass.hxx"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>
#include <odb/view-image.hxx>
#include <odb/view-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // papel
  //
  template <>
  struct class_traits< ::papel >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::papel >
  {
    public:
    typedef ::papel object_type;
    typedef ::papel* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // usuario
  //
  template <>
  struct class_traits< ::usuario >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::usuario >
  {
    public:
    typedef ::usuario object_type;
    typedef ::usuario* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // auditoria
  //
  template <>
  struct class_traits< ::auditoria >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::auditoria >
  {
    public:
    typedef ::auditoria object_type;
    typedef ::auditoria* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // pessoa
  //
  template <>
  struct class_traits< ::pessoa >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::pessoa >
  {
    public:
    typedef ::pessoa object_type;
    typedef ::pessoa* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // denuncia
  //
  template <>
  struct class_traits< ::denuncia >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::denuncia >
  {
    public:
    typedef ::denuncia object_type;
    typedef ::denuncia* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // view_pessoa_denuncia
  //
  template <>
  struct class_traits< ::view_pessoa_denuncia >
  {
    static const class_kind kind = class_view;
  };

  template <>
  class access::view_traits< ::view_pessoa_denuncia >
  {
    public:
    typedef ::view_pessoa_denuncia view_type;
    typedef ::view_pessoa_denuncia* pointer_type;

    static void
    callback (database&, view_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // papel
  //
  template <typename A>
  struct query_columns< ::papel, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // permissoes
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    permissoes_type_;

    static const permissoes_type_ permissoes;
  };

  template <typename A>
  const typename query_columns< ::papel, id_pgsql, A >::id_type_
  query_columns< ::papel, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::papel, id_pgsql, A >::permissoes_type_
  query_columns< ::papel, id_pgsql, A >::
  permissoes (A::table_name, "\"permissoes\"", 0);

  template <typename A>
  struct pointer_query_columns< ::papel, id_pgsql, A >:
    query_columns< ::papel, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::papel, id_pgsql >:
    public access::object_traits< ::papel >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // permissoes
      //
      details::buffer permissoes_value;
      std::size_t permissoes_size;
      bool permissoes_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::papel, id_common >:
    public access::object_traits_impl< ::papel, id_pgsql >
  {
  };

  // usuario
  //
  template <typename A>
  struct pointer_query_columns< ::usuario, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // fk_papel
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    fk_papel_type_;

    static const fk_papel_type_ fk_papel;

    // rg
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    rg_type_;

    static const rg_type_ rg;

    // cpf
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    cpf_type_;

    static const cpf_type_ cpf;

    // nome
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nome_type_;

    static const nome_type_ nome;

    // nome_usuario
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nome_usuario_type_;

    static const nome_usuario_type_ nome_usuario;

    // hash_senha
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    hash_senha_type_;

    static const hash_senha_type_ hash_senha;

    // data_cadastro
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_cadastro_type_;

    static const data_cadastro_type_ data_cadastro;
  };

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::id_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::fk_papel_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  fk_papel (A::table_name, "\"fk_papel\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::rg_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  rg (A::table_name, "\"rg\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::cpf_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  cpf (A::table_name, "\"cpf\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::nome_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  nome (A::table_name, "\"nome\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::nome_usuario_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  nome_usuario (A::table_name, "\"nome_usuario\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::hash_senha_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  hash_senha (A::table_name, "\"hash_senha\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::usuario, id_pgsql, A >::data_cadastro_type_
  pointer_query_columns< ::usuario, id_pgsql, A >::
  data_cadastro (A::table_name, "\"data_cadastro\"", 0);

  template <>
  class access::object_traits_impl< ::usuario, id_pgsql >:
    public access::object_traits< ::usuario >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // fk_papel
      //
      long long fk_papel_value;
      bool fk_papel_null;

      // rg
      //
      details::buffer rg_value;
      std::size_t rg_size;
      bool rg_null;

      // cpf
      //
      details::buffer cpf_value;
      std::size_t cpf_size;
      bool cpf_null;

      // nome
      //
      details::buffer nome_value;
      std::size_t nome_size;
      bool nome_null;

      // nome_usuario
      //
      details::buffer nome_usuario_value;
      std::size_t nome_usuario_size;
      bool nome_usuario_null;

      // hash_senha
      //
      details::buffer hash_senha_value;
      std::size_t hash_senha_size;
      bool hash_senha_null;

      // data_cadastro
      //
      long long data_cadastro_value;
      bool data_cadastro_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct fk_papel_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::usuario, id_common >:
    public access::object_traits_impl< ::usuario, id_pgsql >
  {
  };

  // auditoria
  //
  template <typename A>
  struct pointer_query_columns< ::auditoria, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // acao
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    acao_type_;

    static const acao_type_ acao;

    // usuario_acao
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    usuario_acao_type_;

    static const usuario_acao_type_ usuario_acao;

    // data_hora
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_hora_type_;

    static const data_hora_type_ data_hora;
  };

  template <typename A>
  const typename pointer_query_columns< ::auditoria, id_pgsql, A >::id_type_
  pointer_query_columns< ::auditoria, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::auditoria, id_pgsql, A >::acao_type_
  pointer_query_columns< ::auditoria, id_pgsql, A >::
  acao (A::table_name, "\"acao\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::auditoria, id_pgsql, A >::usuario_acao_type_
  pointer_query_columns< ::auditoria, id_pgsql, A >::
  usuario_acao (A::table_name, "\"usuario_acao\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::auditoria, id_pgsql, A >::data_hora_type_
  pointer_query_columns< ::auditoria, id_pgsql, A >::
  data_hora (A::table_name, "\"data_hora\"", 0);

  template <>
  class access::object_traits_impl< ::auditoria, id_pgsql >:
    public access::object_traits< ::auditoria >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // acao
      //
      details::buffer acao_value;
      std::size_t acao_size;
      bool acao_null;

      // usuario_acao
      //
      long long usuario_acao_value;
      bool usuario_acao_null;

      // data_hora
      //
      long long data_hora_value;
      bool data_hora_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct usuario_acao_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::auditoria, id_common >:
    public access::object_traits_impl< ::auditoria, id_pgsql >
  {
  };

  // pessoa
  //
  template <typename A>
  struct query_columns< ::pessoa, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // estado
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    estado_type_;

    static const estado_type_ estado;

    // rg
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    rg_type_;

    static const rg_type_ rg;

    // cpf
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    cpf_type_;

    static const cpf_type_ cpf;

    // nome
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nome_type_;

    static const nome_type_ nome;

    // idade
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    idade_type_;

    static const idade_type_ idade;

    // detalhes
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    detalhes_type_;

    static const detalhes_type_ detalhes;

    // data_cadastro
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_cadastro_type_;

    static const data_cadastro_type_ data_cadastro;

    // ultimo_update
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    ultimo_update_type_;

    static const ultimo_update_type_ ultimo_update;
  };

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::id_type_
  query_columns< ::pessoa, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::estado_type_
  query_columns< ::pessoa, id_pgsql, A >::
  estado (A::table_name, "\"estado\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::rg_type_
  query_columns< ::pessoa, id_pgsql, A >::
  rg (A::table_name, "\"rg\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::cpf_type_
  query_columns< ::pessoa, id_pgsql, A >::
  cpf (A::table_name, "\"cpf\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::nome_type_
  query_columns< ::pessoa, id_pgsql, A >::
  nome (A::table_name, "\"nome\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::idade_type_
  query_columns< ::pessoa, id_pgsql, A >::
  idade (A::table_name, "\"idade\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::detalhes_type_
  query_columns< ::pessoa, id_pgsql, A >::
  detalhes (A::table_name, "\"detalhes\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::data_cadastro_type_
  query_columns< ::pessoa, id_pgsql, A >::
  data_cadastro (A::table_name, "\"data_cadastro\"", 0);

  template <typename A>
  const typename query_columns< ::pessoa, id_pgsql, A >::ultimo_update_type_
  query_columns< ::pessoa, id_pgsql, A >::
  ultimo_update (A::table_name, "\"ultimo_update\"", 0);

  template <typename A>
  struct pointer_query_columns< ::pessoa, id_pgsql, A >:
    query_columns< ::pessoa, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::pessoa, id_pgsql >:
    public access::object_traits< ::pessoa >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // estado
      //
      bool estado_value;
      bool estado_null;

      // rg
      //
      details::buffer rg_value;
      std::size_t rg_size;
      bool rg_null;

      // cpf
      //
      details::buffer cpf_value;
      std::size_t cpf_size;
      bool cpf_null;

      // nome
      //
      details::buffer nome_value;
      std::size_t nome_size;
      bool nome_null;

      // idade
      //
      int idade_value;
      bool idade_null;

      // detalhes
      //
      details::buffer detalhes_value;
      std::size_t detalhes_size;
      bool detalhes_null;

      // data_cadastro
      //
      long long data_cadastro_value;
      bool data_cadastro_null;

      // ultimo_update
      //
      long long ultimo_update_value;
      bool ultimo_update_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::pessoa, id_common >:
    public access::object_traits_impl< ::pessoa, id_pgsql >
  {
  };

  // denuncia
  //
  template <typename A>
  struct pointer_query_columns< ::denuncia, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // estado
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    estado_type_;

    static const estado_type_ estado;

    // pessoa_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pessoa_denuncia_type_;

    static const pessoa_denuncia_type_ pessoa_denuncia;

    // latitude
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    latitude_type_;

    static const latitude_type_ latitude;

    // longitude
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    longitude_type_;

    static const longitude_type_ longitude;

    // usuario_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    usuario_denuncia_type_;

    static const usuario_denuncia_type_ usuario_denuncia;

    // latitude_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    latitude_denuncia_type_;

    static const latitude_denuncia_type_ latitude_denuncia;

    // longitude_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    longitude_denuncia_type_;

    static const longitude_denuncia_type_ longitude_denuncia;

    // detalhes
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    detalhes_type_;

    static const detalhes_type_ detalhes;

    // data_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_denuncia_type_;

    static const data_denuncia_type_ data_denuncia;
  };

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::id_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::estado_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  estado (A::table_name, "\"estado\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::pessoa_denuncia_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  pessoa_denuncia (A::table_name, "\"pessoa_denuncia\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::latitude_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  latitude (A::table_name, "\"latitude\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::longitude_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  longitude (A::table_name, "\"longitude\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::usuario_denuncia_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  usuario_denuncia (A::table_name, "\"usuario_denuncia\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::latitude_denuncia_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  latitude_denuncia (A::table_name, "\"latitude_denuncia\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::longitude_denuncia_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  longitude_denuncia (A::table_name, "\"longitude_denuncia\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::detalhes_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  detalhes (A::table_name, "\"detalhes\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::denuncia, id_pgsql, A >::data_denuncia_type_
  pointer_query_columns< ::denuncia, id_pgsql, A >::
  data_denuncia (A::table_name, "\"data_denuncia\"", 0);

  template <>
  class access::object_traits_impl< ::denuncia, id_pgsql >:
    public access::object_traits< ::denuncia >
  {
    public:
    struct id_image_type
    {
      int id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id
      //
      int id_value;
      bool id_null;

      // estado
      //
      bool estado_value;
      bool estado_null;

      // pessoa_denuncia
      //
      long long pessoa_denuncia_value;
      bool pessoa_denuncia_null;

      // latitude
      //
      details::buffer latitude_value;
      std::size_t latitude_size;
      bool latitude_null;

      // longitude
      //
      details::buffer longitude_value;
      std::size_t longitude_size;
      bool longitude_null;

      // usuario_denuncia
      //
      long long usuario_denuncia_value;
      bool usuario_denuncia_null;

      // latitude_denuncia
      //
      details::buffer latitude_denuncia_value;
      std::size_t latitude_denuncia_size;
      bool latitude_denuncia_null;

      // longitude_denuncia
      //
      details::buffer longitude_denuncia_value;
      std::size_t longitude_denuncia_size;
      bool longitude_denuncia_null;

      // detalhes
      //
      details::buffer detalhes_value;
      std::size_t detalhes_size;
      bool detalhes_null;

      // data_denuncia
      //
      long long data_denuncia_value;
      bool data_denuncia_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct pessoa_denuncia_tag;
    struct usuario_denuncia_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::denuncia, id_common >:
    public access::object_traits_impl< ::denuncia, id_pgsql >
  {
  };

  // view_pessoa_denuncia
  //
  template <>
  class access::view_traits_impl< ::view_pessoa_denuncia, id_pgsql >:
    public access::view_traits< ::view_pessoa_denuncia >
  {
    public:
    struct image_type
    {
      // id
      //
      long long id_value;
      bool id_null;

      // nome
      //
      details::buffer nome_value;
      std::size_t nome_size;
      bool nome_null;

      // cpf
      //
      details::buffer cpf_value;
      std::size_t cpf_size;
      bool cpf_null;

      // rg
      //
      details::buffer rg_value;
      std::size_t rg_size;
      bool rg_null;

      std::size_t version;
    };

    typedef pgsql::view_statements<view_type> statements_type;

    typedef pgsql::query_base query_base_type;
    struct query_columns;

    static const bool versioned = false;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&);

    static void
    init (view_type&,
          const image_type&,
          database*);

    static const std::size_t column_count = 4UL;

    static query_base_type
    query_statement (const query_base_type&);

    static result<view_type>
    query (database&, const query_base_type&);

    static const char query_statement_name[];
  };

  template <>
  class access::view_traits_impl< ::view_pessoa_denuncia, id_common >:
    public access::view_traits_impl< ::view_pessoa_denuncia, id_pgsql >
  {
  };

  // papel
  //
  // usuario
  //
  template <>
  struct alias_traits<
    ::papel,
    id_pgsql,
    access::object_traits_impl< ::usuario, id_pgsql >::fk_papel_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::usuario, id_pgsql >
  {
    // fk_papel
    //
    typedef
    odb::alias_traits<
      ::papel,
      id_pgsql,
      access::object_traits_impl< ::usuario, id_pgsql >::fk_papel_tag>
    fk_papel_alias_;
  };

  template <typename A>
  struct query_columns< ::usuario, id_pgsql, A >:
    query_columns_base< ::usuario, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // fk_papel
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    fk_papel_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::papel,
        id_pgsql,
        fk_papel_alias_ > >
    fk_papel_pointer_type_;

    struct fk_papel_type_: fk_papel_pointer_type_, fk_papel_column_type_
    {
      fk_papel_type_ (const char* t, const char* c, const char* conv)
        : fk_papel_column_type_ (t, c, conv)
      {
      }
    };

    static const fk_papel_type_ fk_papel;

    // rg
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    rg_type_;

    static const rg_type_ rg;

    // cpf
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    cpf_type_;

    static const cpf_type_ cpf;

    // nome
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nome_type_;

    static const nome_type_ nome;

    // nome_usuario
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    nome_usuario_type_;

    static const nome_usuario_type_ nome_usuario;

    // hash_senha
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    hash_senha_type_;

    static const hash_senha_type_ hash_senha;

    // data_cadastro
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_cadastro_type_;

    static const data_cadastro_type_ data_cadastro;
  };

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::id_type_
  query_columns< ::usuario, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::fk_papel_type_
  query_columns< ::usuario, id_pgsql, A >::
  fk_papel (A::table_name, "\"fk_papel\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::rg_type_
  query_columns< ::usuario, id_pgsql, A >::
  rg (A::table_name, "\"rg\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::cpf_type_
  query_columns< ::usuario, id_pgsql, A >::
  cpf (A::table_name, "\"cpf\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::nome_type_
  query_columns< ::usuario, id_pgsql, A >::
  nome (A::table_name, "\"nome\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::nome_usuario_type_
  query_columns< ::usuario, id_pgsql, A >::
  nome_usuario (A::table_name, "\"nome_usuario\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::hash_senha_type_
  query_columns< ::usuario, id_pgsql, A >::
  hash_senha (A::table_name, "\"hash_senha\"", 0);

  template <typename A>
  const typename query_columns< ::usuario, id_pgsql, A >::data_cadastro_type_
  query_columns< ::usuario, id_pgsql, A >::
  data_cadastro (A::table_name, "\"data_cadastro\"", 0);

  // auditoria
  //
  template <>
  struct alias_traits<
    ::usuario,
    id_pgsql,
    access::object_traits_impl< ::auditoria, id_pgsql >::usuario_acao_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::auditoria, id_pgsql >
  {
    // usuario_acao
    //
    typedef
    odb::alias_traits<
      ::usuario,
      id_pgsql,
      access::object_traits_impl< ::auditoria, id_pgsql >::usuario_acao_tag>
    usuario_acao_alias_;
  };

  template <typename A>
  struct query_columns< ::auditoria, id_pgsql, A >:
    query_columns_base< ::auditoria, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // acao
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    acao_type_;

    static const acao_type_ acao;

    // usuario_acao
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    usuario_acao_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::usuario,
        id_pgsql,
        usuario_acao_alias_ > >
    usuario_acao_pointer_type_;

    struct usuario_acao_type_: usuario_acao_pointer_type_, usuario_acao_column_type_
    {
      usuario_acao_type_ (const char* t, const char* c, const char* conv)
        : usuario_acao_column_type_ (t, c, conv)
      {
      }
    };

    static const usuario_acao_type_ usuario_acao;

    // data_hora
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_hora_type_;

    static const data_hora_type_ data_hora;
  };

  template <typename A>
  const typename query_columns< ::auditoria, id_pgsql, A >::id_type_
  query_columns< ::auditoria, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::auditoria, id_pgsql, A >::acao_type_
  query_columns< ::auditoria, id_pgsql, A >::
  acao (A::table_name, "\"acao\"", 0);

  template <typename A>
  const typename query_columns< ::auditoria, id_pgsql, A >::usuario_acao_type_
  query_columns< ::auditoria, id_pgsql, A >::
  usuario_acao (A::table_name, "\"usuario_acao\"", 0);

  template <typename A>
  const typename query_columns< ::auditoria, id_pgsql, A >::data_hora_type_
  query_columns< ::auditoria, id_pgsql, A >::
  data_hora (A::table_name, "\"data_hora\"", 0);

  // pessoa
  //
  // denuncia
  //
  template <>
  struct alias_traits<
    ::pessoa,
    id_pgsql,
    access::object_traits_impl< ::denuncia, id_pgsql >::pessoa_denuncia_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::usuario,
    id_pgsql,
    access::object_traits_impl< ::denuncia, id_pgsql >::usuario_denuncia_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::denuncia, id_pgsql >
  {
    // pessoa_denuncia
    //
    typedef
    odb::alias_traits<
      ::pessoa,
      id_pgsql,
      access::object_traits_impl< ::denuncia, id_pgsql >::pessoa_denuncia_tag>
    pessoa_denuncia_alias_;

    // usuario_denuncia
    //
    typedef
    odb::alias_traits<
      ::usuario,
      id_pgsql,
      access::object_traits_impl< ::denuncia, id_pgsql >::usuario_denuncia_tag>
    usuario_denuncia_alias_;
  };

  template <typename A>
  struct query_columns< ::denuncia, id_pgsql, A >:
    query_columns_base< ::denuncia, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        unsigned int,
        pgsql::id_integer >::query_type,
      pgsql::id_integer >
    id_type_;

    static const id_type_ id;

    // estado
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    estado_type_;

    static const estado_type_ estado;

    // pessoa_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    pessoa_denuncia_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::pessoa,
        id_pgsql,
        pessoa_denuncia_alias_ > >
    pessoa_denuncia_pointer_type_;

    struct pessoa_denuncia_type_: pessoa_denuncia_pointer_type_, pessoa_denuncia_column_type_
    {
      pessoa_denuncia_type_ (const char* t, const char* c, const char* conv)
        : pessoa_denuncia_column_type_ (t, c, conv)
      {
      }
    };

    static const pessoa_denuncia_type_ pessoa_denuncia;

    // latitude
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    latitude_type_;

    static const latitude_type_ latitude;

    // longitude
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    longitude_type_;

    static const longitude_type_ longitude;

    // usuario_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    usuario_denuncia_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::usuario,
        id_pgsql,
        usuario_denuncia_alias_ > >
    usuario_denuncia_pointer_type_;

    struct usuario_denuncia_type_: usuario_denuncia_pointer_type_, usuario_denuncia_column_type_
    {
      usuario_denuncia_type_ (const char* t, const char* c, const char* conv)
        : usuario_denuncia_column_type_ (t, c, conv)
      {
      }
    };

    static const usuario_denuncia_type_ usuario_denuncia;

    // latitude_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    latitude_denuncia_type_;

    static const latitude_denuncia_type_ latitude_denuncia;

    // longitude_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    longitude_denuncia_type_;

    static const longitude_denuncia_type_ longitude_denuncia;

    // detalhes
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    detalhes_type_;

    static const detalhes_type_ detalhes;

    // data_denuncia
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::time_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    data_denuncia_type_;

    static const data_denuncia_type_ data_denuncia;
  };

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::id_type_
  query_columns< ::denuncia, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::estado_type_
  query_columns< ::denuncia, id_pgsql, A >::
  estado (A::table_name, "\"estado\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::pessoa_denuncia_type_
  query_columns< ::denuncia, id_pgsql, A >::
  pessoa_denuncia (A::table_name, "\"pessoa_denuncia\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::latitude_type_
  query_columns< ::denuncia, id_pgsql, A >::
  latitude (A::table_name, "\"latitude\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::longitude_type_
  query_columns< ::denuncia, id_pgsql, A >::
  longitude (A::table_name, "\"longitude\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::usuario_denuncia_type_
  query_columns< ::denuncia, id_pgsql, A >::
  usuario_denuncia (A::table_name, "\"usuario_denuncia\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::latitude_denuncia_type_
  query_columns< ::denuncia, id_pgsql, A >::
  latitude_denuncia (A::table_name, "\"latitude_denuncia\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::longitude_denuncia_type_
  query_columns< ::denuncia, id_pgsql, A >::
  longitude_denuncia (A::table_name, "\"longitude_denuncia\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::detalhes_type_
  query_columns< ::denuncia, id_pgsql, A >::
  detalhes (A::table_name, "\"detalhes\"", 0);

  template <typename A>
  const typename query_columns< ::denuncia, id_pgsql, A >::data_denuncia_type_
  query_columns< ::denuncia, id_pgsql, A >::
  data_denuncia (A::table_name, "\"data_denuncia\"", 0);

  // view_pessoa_denuncia
  //
  struct access::view_traits_impl< ::view_pessoa_denuncia, id_pgsql >::query_columns
  {
    // pessoa
    //
    typedef
    odb::pointer_query_columns<
      ::pessoa,
      id_pgsql,
      odb::access::object_traits_impl< ::pessoa, id_pgsql > >
    pessoa;

    // denuncia
    //
    typedef
    odb::pointer_query_columns<
      ::denuncia,
      id_pgsql,
      odb::access::object_traits_impl< ::denuncia, id_pgsql > >
    denuncia;
  };
}

#include "AllClass-odb.ixx"

#include <odb/post.hxx>

#endif // ALL_CLASS_ODB_HXX
