/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "denuncia" CASCADE;

DROP TABLE IF EXISTS "pessoa" CASCADE;

DROP TABLE IF EXISTS "auditoria" CASCADE;

DROP TABLE IF EXISTS "usuario" CASCADE;

DROP TABLE IF EXISTS "papel" CASCADE;

CREATE TABLE "papel" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "permissoes" TEXT NOT NULL);

CREATE TABLE "usuario" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "fk_papel" BIGINT NOT NULL,
  "rg" TEXT NOT NULL,
  "cpf" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "nome_usuario" TEXT NOT NULL,
  "hash_senha" TEXT NOT NULL,
  "data_cadastro" BIGINT NOT NULL,
  CONSTRAINT "fk_papel_fk"
    FOREIGN KEY ("fk_papel")
    REFERENCES "papel" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "auditoria" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "acao" TEXT NOT NULL,
  "usuario_acao" BIGINT NOT NULL,
  "data_hora" BIGINT NOT NULL,
  CONSTRAINT "usuario_acao_fk"
    FOREIGN KEY ("usuario_acao")
    REFERENCES "usuario" ("id")
    INITIALLY DEFERRED);

CREATE TABLE "pessoa" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "estado" BOOLEAN NOT NULL,
  "rg" TEXT NOT NULL,
  "cpf" TEXT NOT NULL,
  "nome" TEXT NOT NULL,
  "idade" INTEGER NOT NULL,
  "detalhes" TEXT NOT NULL,
  "data_cadastro" BIGINT NOT NULL,
  "ultimo_update" BIGINT NOT NULL);

CREATE TABLE "denuncia" (
  "id" SERIAL NOT NULL PRIMARY KEY,
  "estado" BOOLEAN NOT NULL,
  "pessoa_denuncia" BIGINT NOT NULL,
  "latitude" TEXT NOT NULL,
  "longitude" TEXT NOT NULL,
  "usuario_denuncia" BIGINT NOT NULL,
  "latitude_denuncia" TEXT NOT NULL,
  "longitude_denuncia" TEXT NOT NULL,
  "detalhes" TEXT NOT NULL,
  "data_denuncia" BIGINT NOT NULL,
  CONSTRAINT "pessoa_denuncia_fk"
    FOREIGN KEY ("pessoa_denuncia")
    REFERENCES "pessoa" ("id")
    INITIALLY DEFERRED,
  CONSTRAINT "usuario_denuncia_fk"
    FOREIGN KEY ("usuario_denuncia")
    REFERENCES "usuario" ("id")
    INITIALLY DEFERRED);

